version: 0.2

env:
  parameter-store:
    database_username: "/ci/database/username"
    database_password: "/ci/database/password"
    database_url: "/ci/database/url"

phases:
  install:
   runtime-versions:
      java: corretto21

  pre_build:
    commands:
      - git submodule sync --recursive
      - git submodule update --init --recursive
      - sed -i "s|jdbc\.password=.*|jdbc.password=${database_password}|" project/src/main/resources/application.properties
      - sed -i "s|jdbc\.username=.*|jdbc.username=${database_username}|" project/src/main/resources/application.properties
      - sed -i "s|jdbc\.url=.*|jdbc.url=jdbc:mysql://${database_url}/accounts?useUnicode=true\&characterEncoding=UTF-8\&zeroDateTimeBehavior=convertToNull|" project/src/main/resources/application.properties

  build:
    commands:
      - cd project
      - mvn install
      - cd ..
      - mv project/target/*.war project/target/ROOT.war

artifacts:
  base-directory: project/target
  files:
     - '*.war'
  discard-paths: yes
  name: application.zip
